CREATE TABLE roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

ALTER TABLE roles
ADD COLUMN created_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE roles
ADD COLUMN updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP;
