management:
  endpoints:
    web:
      exposure:
        include: health, info

security:
 jwt:
   secret-key: ReplaceThisWithAtLeastA256BitSecretKeyReplaceThisWithAtLeastA256BitSecretKey
   expiration: 3600000