management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pradeep
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

security:
 jwt:
   secret-key: ReplaceThisWithAtLeastA256BitSecretKeyReplaceThisWithAtLeastA256BitSecretKey
   expiration: 3600000