management:
  endpoints:
    web:
      exposure:
        include: health, info
spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
 jwt:
   secret-key: ReplaceThisWithAtLeastA256BitSecretKeyReplaceThisWithAtLeastA256BitSecretKey
   expiration: 3600000